name: test

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Execute tests via PHPUnit
      run: vendor/bin/phpunit --coverage-clover clover.xml
    - name: codecov
      env:
        CODECOV_TOKEN:  ${{ secrets.CODECOV_TOKEN }}
      run: bash <(curl -s https://codecov.io/bash)
